Update Select.php (#2241)
* Update Select.php

This will fix (in pimcore 4.6.3) so that you don't fetch columnLength (that's already in columnType) -> varchar(255)(190).

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(190) NULL' at line 1 in /opt/pim/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

Zend_Db_Statement_Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(190) NULL' at line 1, query was: ALTER TABLE `object_collection_DeviceBatteryTimes_1` CHANGE COLUMN `Standard` `Standard` varchar(255)(190) NULL; in /opt/pim/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

* Update Select.php

Updating pimcore4 with legacy support from pimcore5 with tip from @dpfaffenbauer