Removed Object.php
- Removed Object.php because php linters are complaining about it:

```
Checked 2390 files in 9.1 seconds
Syntax error found in 1 file

------------------------------------------------------------
Parse error: ./pimcore/models/Object.php:30
    28|     if (version_compare(PHP_VERSION, '7.2.0', '<')) {
    29|         if (!\Pimcore\Tool::classExists('Pimcore\\Model\\Object')) {
  > 30|             class Object extends \Pimcore\Model\DataObject\AbstractObject
    31|             {
    32|             }
Fatal error: Cannot use 'Object' as class name as it is reserved
ERROR: Job failed: exit code 1
```