fix: Listing::getTotalCount() should use connected parameters (#18907)
* fix: Listing::getTotalCount() should use connected parameters

Error: When a listing was prepared containing a `addConditionParam('field = ?', 'value'`) and also containing a `addGroupBy()` then Listing::getTotalCount() resulted in SQL errors.
Caused by: Parameters added to the QueryBuilder were not passed to `db->fetchOne()` in that particular scenario.
Resolved with: Adding parameters, expanding integration test, updating documentation.

* Update tests/Model/Asset/ListingTest.php

* Update tests/Model/Asset/ListingTest.php

---------

Co-authored-by: Marco <89011527+mcop1@users.noreply.github.com>