fix: block fields should rewrite references
Error: when using "Paste recursive, updating references" relation fields
 within blocks were not updated
Caused by: ClassDefinition\Data\Block not implementing
 IdRewriterInterface
Resolved with: implement IdRewriterInterface and rewriteIds method