fix: error in migration CoreBundle, IF EXISTS is not a valid MySQL 8 statement
Error: An exception occurred while executing 'ALTER TABLE `object_metadata_14` DROP FOREIGN KEY IF EXISTS `fk_object_metadata_14__o_id`':
   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax;
   check the manual that corresponds to your MySQL server version for the right syntax to use near '
   IF EXISTS `fk_object_metadata_14__o_id`' at line 1
Caused by: "IF EXISTS" is valid in MariaDB but not in MySQL 8
Resolved with: checking existence via metadata