fix: determine object aware fields at wakeup time
Error: migrated versions with localized fields can't be displayed
Caused by: 'localizedfields' not included in the __objectAwareFields array at sleep time
Resolved with: when loading version data, checking all fields whether they implement the ObjectAwareFieldInterface