[Fix] create language inherited child didn't set the controller & template (#11641)
* Fix DocType::getById() should return null on empty id

Error: When creating a new document translation variant the controller+template weren't set.

Caused by: DocType::getById() returning a DocType object (with empty properties though) on null value id's. The if-elsif flow in the DocumentController::addAction() then (unjustly) skipped the 'translationsBaseDocument' logic.

Resolved by: Adding an if(empty($id)) check to the getById() method

* Fix DocType\Dao::getById() shouldn't return anything